services:
  openvpn:
    image: drakula21/openvpn-image
    container_name: ovpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /opt/openvpn-image/openvpn:/etc/openvpn
      - /opt/openvpn-image/AdGuardHome:/opt/AdGuardHome
    ports:
      - "1194:1194"
      - "3000:3000"
      - "80:80"
    restart: unless-stopped

